version: '3'
services:
        jupyter:
                build: docker/jupyter
                ports:
                - 8888
                volumes:
                - ${LOCAL_DEVELOP_DIR}:/home/jovyan/develop
                - ${LOCAL_DATA_DIR}:/home/jovyan/data
                - ${LOCAL_DELIVERY_DIR}:/home/jovyan/delivery
                - ${LOCAL_WORK_DIR}:/home/jovyan/work
                command: "start-notebook.sh \
                          --NotebookApp.password=${ACCESS_TOKEN}
                          --NotebookApp.token=${TOKEN}"
                stdin_open: true
                tty: true
        python:
                image: python:3.7.0
                stdin_open: true
                tty: true
